spring:
  application:
    name: pting

  config:
    import:
      optional:file:.env[.properties] # 루트 디렉토리에 .env 파일이 있다면(local) 가져오고, 없으면(release) 무시하고 진행

  profiles:
    include: auth

  sql:
    init:
      mode: embedded
      data-locations: classpath:static/sql/data.sql
      schema-locations: classpath:static/sql/schema.sql

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: pting.dev@gmail.com
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

firebase:
  credentials: classpath:firebase/pting-sdk-credentials.json

app:
  domain: ${SERVER_ADDRESS}
