auth:
  jwt:
    secret: ${JWT_SECRET}

  oauth2:
    kakao:
      client-id: ${KAKAO_CLIENT_ID}
      client-secret: ${KAKAO_CLIENT_SECRET}
      auth-uri: https://kauth.kakao.com/oauth/authorize
      redirect-uri: ${CLIENT_ADDRESS}/auth/kakao/callback
      token-uri: https://kauth.kakao.com/oauth/token
      info-uri: https://kapi.kakao.com/v2/user/me
    google:
      client-id: ${GOOGLE_CLIENT_ID}
      client-secret: ${GOOGLE_CLIENT_SECRET}
      auth-uri: https://accounts.google.com/o/oauth2/v2/auth
      redirect-uri: ${SERVER_ADDRESS}/api/v1/auth/google/callback
      token-uri: https://www.googleapis.com/oauth2/v4/token
      info-uri: https://www.googleapis.com/oauth2/v3/userinfo
