name: Deploy Spring Boot to EC2

on:
  push:
    branches:
      - feature/merge
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Firebase Credentials
        uses: jsdaniell/create-json@v1.2.3
        with:
          name: pting-sdk-credentials.json
          json: ${{ secrets.FIREBASE_CREDENTIALS }}
          dir: 'src/main/resources/firebase/'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle (skip integration tests)
        env:
          GRADLE_OPTS: "-Dci=true" # 통합 테스트가 제외될 수 있도록 ci 프로퍼티 설정
        run: ./gradlew build

      - name: Transfer JAR to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_SSH_PRIVATE_KEY }}
          source: "build/libs/*.jar"
          target: "/home/ubuntu/app"

      - name: Execute deployment script on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_SSH_PRIVATE_KEY }}
          script: |
            /home/ubuntu/app/deploy.sh
